GC_beta/GC_beta/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static

# from rest_framework import routers
from rest_framework_nested import routers
from transcript_handler import views

router = routers.SimpleRouter()
# router.register(r'dashboard', views.dashboard, 'dashboard')
router.register(r'universities', views.UniversityViewSet, 'university')
router.register(r'students', views.StudentViewSet, 'students')



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('transcript_handler.urls', namespace='transcript_handler')),
    # url(r'^api/', include((router.urls, ''), namespace='api'))
    path('api/', include(router.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

GC_beta/transcript_handler/urls.py
from django.urls import path
from . import views
from rest_framework import routers

app_name = 'transcript_handler'
# router = routers.DefaultRouter()
# router.register(r'university', views.UniversityViewSet)

urlpatterns = [
    # path('universities/', views.university_list),
    # path('students/', views.student_list),
    # path('/<int:pk>/', views.snippet_detail),
    path('', views.dashboard, name='dashboard'),
    path('api/students/<pk>/transcript', views.student_transcript, name='student_transcript'),
    path('api/students/<pk>/updateTranscript', views.update_transcript, name='update_transcript'),
    path('api/students/<pk>/updateConsolidatedData', views.update_Consolidated_Data, name='update_Consolidated_Data'),
    path('test', views.test_route),
    path('get-usage', views.get_engine_usage)
]

GC_beta/transcript_handler/models.py
# from djongo import models
from mongoengine import *
from abc import ABC, ABCMeta, abstractmethod

"""
Update:
    1. Rocket.
"""


# class Engine(Document):
#     provider = StringField()
#     key = StringField()
#     usage = EmbeddedDocumentField()
#
# class EngineUsage(EmbeddedDocument):
#     credit

class Identifier(EmbeddedDocument):
    """
    Basically the metadata for the transcript. no idea what they could be.
    """
    feature1 = StringField()
    feature2 = IntField()
    feature3 = IntField()


class Department(EmbeddedDocument):
    name = StringField(max_length=40)
    identifier = EmbeddedDocumentField(Identifier)


class University(Document):
    name = StringField(max_length=100)
    departments = ListField(EmbeddedDocumentField(Department))
    identifier = EmbeddedDocumentField(Identifier)

    def test_method(self, string):
        return self.name + string

    def __str__(self):
        return f"{self.name}"


class ProcessedTable(EmbeddedDocument):
    page = IntField()  # on which page
    table_num = IntField()  # which table
    table_data = StringField()  # json, will be restored to dataframe?
    image_path = StringField()  # localhost abs path for now, under port 8080
    modified = IntField(default=0)


class Transcript(EmbeddedDocument):
    """
    1. the raw_file field should be FileField which serves static files locally. Not a concern for now.
    2. the processed_data should be some normalized data. Not a concern for now.
    """
    mock_raw_file = StringField(default="")
    processed_data = ListField(EmbeddedDocumentField(ProcessedTable), default=[])
    status = IntField(default=0)  # 0 for not processed, 1 for processing, 2 for done
    raw_file = FileField()
    valid_pages = ListField(default=[])


class Education(EmbeddedDocument):
    """
    This would be just a wrapper for retrieving identifiers
    """
    university = StringField(max_length=100, null=True)
    department = StringField(max_length=40, null=True)


class TabContent(EmbeddedDocument):
    name = StringField(required=True)
    GPA = StringField()
    data = StringField()


class ConsolidatedData(EmbeddedDocument):
    tabs = ListField(default=[])
    tabContent = ListField(EmbeddedDocumentField(TabContent), default=[])


class Student(Document):
    """
    Anyhow, students are the subjects that we are interested.
    """
    name = StringField(max_length=40)
    gpa = DecimalField(default=0.00, min_value=0, max_value=4, precision=2)
    transcript = EmbeddedDocumentField(Transcript, default=Transcript())
    consolidatedData = EmbeddedDocumentField(ConsolidatedData, default=ConsolidatedData())
    education = EmbeddedDocumentField(Education, default=Education())
    status = StringField(default="NEW")


class score_scheme(EmbeddedDocument):
    score_from = DecimalField()
    score_to = DecimalField()
    usgrade = StringField() 


class grade_scheme(EmbeddedDocument):
    transcript_grade = StringField()
    scale = DecimalField()
    usgrade = StringField()


class Conversion(Document):
    university = StringField()
    country = StringField()
    SG_base = StringField()
    score_scheme = EmbeddedDocumentField(score_scheme, default=score_scheme)
    grade_scheme = EmbeddedDocumentField(grade_scheme, default = grade_scheme)


class StudentTable(Document):
    course = StringField()
    credit = StringField()
    grade_point = StringField()
    score = StringField()
    meta = {
        'collection': 'student_temp',
        'auto_create_index': True,
    }

class SingletonABCMeta(ABCMeta):
    _instances = {}

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super(SingletonABCMeta, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class GenericTranscriptHandler(metaclass=SingletonABCMeta):

    def __init__(self):
        pass

    # @abstractmethod
    # def process_transcript(self, student):
    #     pass

    @abstractmethod
    def prepare_transcript(self, student):
        pass

    @abstractmethod
    def calculate_gpa(self, student):
        pass

    @abstractmethod
    def get_usage(self):
        pass

GC_beta/transcript_handler/forms.py
from django import forms

# class DashboardForm(forms.Form):
#     init_button = forms.

GC_beta/transcript_handler/views.py
from cProfile import run
import io
import os
from pdb import runcall
from threading import Thread
from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from rest_framework_mongoengine.viewsets import ModelViewSet, GenericViewSet
from django.core.files.storage import default_storage

from .Run_Data_Check import run_data_check
from .Run_School_Template import run_school_template

from .handlers import ExtractTableHandler
from .models import  ConsolidatedData, ProcessedTable, StudentTable, TabContent, University, Student, Department, Identifier, Transcript, Education
from .serializers import UniversitySerializer, StudentSerializer, TranscriptSerializer
from .utils import extract_pages_from_raw_file, get_transcripts_and_dump_into_disk
from GC_beta.settings import BASE_DIR
import json
from bson import json_util
from .System_GPA import GPA



@csrf_exempt
def dashboard(request):
    if request.method == "POST":
        University.objects().delete({})
        Student.objects.all().delete({})
        # TODO: init some documents down here
        u1 = University(name="SIT", identifier=Identifier(feature1="7", feature2=8, feature3=9))
        d1 = Department(name="D1", identifier=Identifier(feature1="7", feature2=8, feature3=9))
        d2 = Department(name="D2", identifier=Identifier(feature1="7", feature2=8, feature3=9))
        u1.departments = [d1, d2]
        u1.save()
        s1 = Student(name="s1", transcript=Transcript(mock_raw_file="ABC"),
                     education=Education(university=u1.name, department=d1.name))
        s2 = Student(name="s2", transcript=Transcript(mock_raw_file="EFG"),
                     education=Education(university=u1.name, department=d1.name))
        s1.save()
        s2.save()
        context = {
            "message": "all collections flushed, dummy data populated."
        }
        # disconnect(alias='default')
        return render(request, 'dashboard.html', context)
    elif request.method == "GET":
        return render(request, 'dashboard.html')


# save for later, don't delete them

# @csrf_exempt
# def university_list(request):
#     """
#     List all code snippets, or create a new snippet.
#     """
#     if request.method == 'GET':
#         universities = University.objects.all()
#         serializer = UniversitySerializer(universities, many=True)
#         return JsonResponse(serializer.data, safe=False)
#
#     elif request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = UniversitySerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return JsonResponse(serializer.data, status=201)
#         return JsonResponse(serializer.errors, status=400)
#
#
# @csrf_exempt
# def student_list(request):
#     """
#     List all code snippets, or create a new snippet.
#     """
#     if request.method == 'GET':
#         students = Student.objects.all()
#         serializer = StudentSerializer(students, many=True)
#         return JsonResponse(serializer.data, safe=False)
#
#     elif request.method == 'POST':
#         data = JSONParser().parse(request)
#         serializer = StudentSerializer(data=data)
#         if serializer.is_valid():
#             serializer.save()
#             return JsonResponse(serializer.data, status=201)
#         return JsonResponse(serializer.errors, status=400)

@csrf_exempt
def test_route(request):
    print(request)
    return JsonResponse({}, status=200)


@csrf_exempt
def get_engine_usage(request):
    try:
        usage_info = ExtractTableHandler.get_usage()
        return JsonResponse({'enginesUsage': [usage_info]}, status=200)
    except:
        return JsonResponse({'error': 'something went wrong'}, status=404)

@csrf_exempt
def update_transcript(request, pk):
    if request.method == "POST":
        try:
            student = Student.objects.get(id=pk)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=404)

        table_data = json.loads(request.body)
        tables = []

        for table in table_data['data']:
            new_table = ProcessedTable(page = table['page'], table_num = table['table_num'], table_data = table['table_data'], image_path = table['image_path'], modified = 1)            
            tables.append(new_table)
        
        student.transcript.processed_data = tables
        # student.consolidatedData = ConsolidatedData(tabs=[], tabContent=[])
        student.save()

    return JsonResponse({}, status=200)

@csrf_exempt
def update_Consolidated_Data(request, pk):
    if request.method == "POST":
        try:
            student = Student.objects.get(id=pk)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=404)
        
        data = json.loads(request.body)
        tabs = list(data['data']['tabs'])
        tabData = []
        for element in data['data']['tabData']:
            tabData.append(TabContent(name = element['tabName'], data = json.dumps(element['data']), GPA = element['gpa']))
        
        student.consolidatedData = ConsolidatedData(tabs = tabs, tabContent = tabData) 
        student.save()
    return JsonResponse({}, status=200)

@csrf_exempt
def student_transcript(request, pk):
    if request.method == 'GET':
        try:
            student = Student.objects.get(id=pk)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=404)
        transcript = student.transcript
        if not request.GET.get('action'):  # default behavior, get the transcript of a student
            serializer = TranscriptSerializer(transcript)
            return JsonResponse(serializer.data, status=200)

        elif request.GET.get('action') == 'calculate':  # get the transcript processing
            gpa = ExtractTableHandler.calculate_gpa(student)
            return JsonResponse({'gpa': gpa}, status=200)

        elif request.GET.get('action') == 'status':  # get the status of the transcript's process
            status = student.transcript.status
            return JsonResponse({'status': status}, status=200)

        elif request.GET.get('action') == 'prepare':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            if not len(student.transcript.valid_pages) > 0:
                return JsonResponse({'error': "No uploaded file found."}, status=404)
            #succeed = ExtractTableHandler.prepare_transcript(student)
            succeed = ExtractTableHandler.get_extractTable_data(student)
            return JsonResponse({'message': "okay"}, status=200) if succeed else JsonResponse(
                {'message': "something went wrong."}, status=200)
 
        elif request.GET.get('action') == 'view':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            processed_transcripts = student.transcript.processed_data
            tables_in_dict = [json.loads(x.to_json()) for x in processed_transcripts]
            return JsonResponse({'student_name': student.name, 'tables': tables_in_dict})

        elif request.GET.get('action') == 'check_transcript_data':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            processed_data = run_data_check(student)
            print(processed_data)
            return JsonResponse({'student_name': student.name, 'data':str(processed_data)})

        elif request.GET.get('action') == 'viewtables':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            
            if(len(student.consolidatedData.tabContent) == 0):
                output_dict = run_school_template(student)
                student.consolidatedData = output_dict
                student.save()
                
            processed_transcripts = student.consolidatedData
            consolidated_data_dict = student.consolidatedData.to_mongo()
            json_string = json.dumps(consolidated_data_dict, default=json_util.default)

            #tables_in_dict = [json.loads(x.to_json()) for x in processed_transcripts]
            return JsonResponse({'student_name': student.name, 'data': json_string})

        elif request.GET.get('action') == 'calculateGPA':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            tabName = request.GET.get('tabname')
            result = GPA(student.id, tabName)
            gpa = result.calculate_GPA()
            return JsonResponse({'student_name': student.name, 'result': str(gpa)})
        
        elif request.GET.get('action') == 'reset_consolidated_data':
            student = None
            try:
                student = Student.objects.get(id=pk)
            except:
                return JsonResponse({'error': "student not found."}, status=404)
            
            student.consolidatedData = ConsolidatedData(tabs=[], tabContent=[])
            student.save()
            return JsonResponse({'student_name': student.name, 'result': "success"})
        

    elif request.method == 'POST':  # add new transcripts, default is override
        studentId = pk
        try:
            student = Student.objects.get(id=studentId)
        except:
            print(f'student {studentId} not found.')

GC_beta/transcript_handler/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>just a temp</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<header>
    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">blablabla</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <a class="nav-link" href="#">Sign out</a>
            </li>
        </ul>
    </header>
</header>
<body>
<div class="container-fluid">
    <div class="row">
        <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
            <div class="position-sticky pt-3">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'transcript_handler:dashboard' %}">
                            <span data-feather="home"></span>
                            Dashboard
                        </a>
                    </li>
                </ul>

                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                    <span>Records</span>
                    <a class="link-secondary" href="#" aria-label="Add a new report">
                        <span data-feather="plus-circle"></span>
                    </a>
                </h6>
                <ul class="nav flex-column mb-2">
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Students
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file-text"></span>
                            Universities
                        </a>
                    </li>
                </ul>
            </div>
        </nav>

        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">{%block title%}{%endblock%}</h1>
            </div>
            {% block content %} {% endblock %}
            <!--            <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>-->
        </main>
    </div>
</div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
</html>

GC_beta/transcript_handler/templates/dashboard.html
{% extends "base.html" %}
{% block title%} Dashboard {%endblock%}
{% block content %}
This is DashBoard
<p>{{ message }}</p>
<form action="{% url 'transcript_handler:dashboard' %}" method="post">
    <button class="btn btn-primary mb-2">
        Flush DB
    </button>
</form>
{% endblock %}